#https://tomverbeure.github.io/2019/08/03/Video-Timings-Calculator.html
Section "Device"
    Identifier  "DummyDevice"
    Driver      "dummy"
    VideoRam    8192
EndSection

Section "Monitor"
    Identifier   "DummyMonitor"
    HorizSync    10.0-25.0
    VertRefresh  15.0-25.0
    Modeline     "1920x1080" 52.5  1920 1968 2160 2400 1080 1083 1088 1096
    Modeline     "1360x768"  26.25 1360 1400 1528 1696  768  771  781  787
    Modeline     "1024x768"  19.75 1024 1056 1152 1280  768  771  775  781
EndSection

Section "Screen"
    Identifier    "WXGA"
    Device        "DummyDevice"
    Monitor       "DummyMonitor"
    DefaultDepth  16
    SubSection "Display"
        Depth  16
        Modes  "1920x1080" "1360x768" "1024x768"
    EndSubSection
EndSection
