#NAME                           GLW MODEL
MEDIUM_BACKPACK                 82  w_loot_char_backpack_medium.rmdl @i
HEAVY_BACKPACK                  81  w_loot_char_backpack_heavy.rmdl @i
SHOTGUN_BOLT                    66  w_loot_wep_mods_mag_v3b.rmdl @i
SHOTGUN_AMMO                    66  w_loot_wep_ammo_shg.rmdl @i
MOZAMBIQUE                      66  /pstl_sa3/ /mozambique/
EVA-8                           66  /eva8/ @i
PEACEKEEPER                     66  /peacekeeper/ @i
MASTIFF                         66  /mastiff/ /mastiff_stgn/
BARREL_STBLZR                   54  w_loot_wep_mods_suppr_v2b.rmdl @i
LASER_SIGHT                     54  w_loot_wep_mods_lasersight_v1.rmdl @i
STNDRD_STOCK                    54  w_loot_wep_iso_stock_folded_regular.rmdl @i
SNIPER_STOCK                    54  w_loot_wep_iso_stock_folded_sniper.rmdl @i
HEAVY_MAG                       52  w_loot_wep_mods_mag_v2b.rmdl @i
HEAVY_AMMO                      52  w_loot_wep_ammo_hc.rmdl @i
FLATLINE                        52  /flatline/ @i
HEMLOK                          52  /m1a1_hemlok/ /hemlok/
PROWLER                         52  /prowler/ /prowler_smg/
30-30                           52  /3030repeater/ /repeater3030/
RAMPAGE                         52  /dragon/ @i
C.A.R.                          52  /car/ @i
LIGHT_MAG                       37  w_loot_wep_mods_mag_v1b.rmdl @i
LIGHT_AMMO                      37  w_loot_wep_ammo_sc.rmdl @i
G7_SCOUT                        37  /g7/ /g2/
SPITFIRE                        37  /lmg_hemlok/ /spitfire/
R-301                           37  /r301/ /rspn101/
R-99                            37  /r97/ /r99/
ALTERNATOR                      37  /alternator_smg/ /alternator/
P2020                           37  /p2011/ /p2020/
ULTIMATE_ACCEL                  34  w_loot_wep_iso_ultimate_accelerant.rmdl @i
MED_KIT                         34  w_loot_wep_iso_health_main_large.rmdl @i
SHIELD_BATTERY                  34  w_loot_wep_iso_shield_battery_large.rmdl @i
HEAT_SHIELD                     34  loot_void_ring.rmdl @i
MOBILE_RESPAWN                  34  beacon_capsule_01.rmdl @i
EVAC_TOWER                      34  evac_tower_loot.rmdl @i
2X_HCOG                         33  w_loot_wep_mods_optic_cq_hcog_r2.rmdl @i
1X-2X_HOLO                      33  w_loot_wep_mods_optic_cq_holo_var_2x.rmdl @i
3X_HCOG                         33  w_loot_wep_mods_optic_rng_hcog_acgs.rmdl @i
2X-4X_AOG                       33  w_loot_wep_mods_optic_rng_aog_var_r1.rmdl @i
6X_SNIPER                       33  w_loot_wep_mods_optic_sni_dcom.rmdl @i
4X-8X_SNIPER                    33  w_loot_wep_mods_optic_sni_var_talon.rmdl @i
4X-10X_SNIPER                   33  w_loot_wep_mods_optic_sni_threat_wyeon.rmdl @i
ENERGY_MAG                      32  w_loot_wep_mods_mag_energy_v1.rmdl @i
ENERGY_AMMO                     32  w_loot_wep_ammo_nrg.rmdl @i
NEMESIS                         32  /nemesis/ @i
VOLT                            32  /hemlok_smg/ /volt/
TRIPLE_TAKE                     32  /doubletake/ /tripletake/
L-STAR                          32  /lstar/ @i
DEVOTION                        32  /hemlock_br/ /devotion/
HAVOC                           32  /beam_ar/ /havoc/
RE-45                           32  /p2011_auto/ /re45/
SNIPER_MAG                      4   w_loot_wep_mods_mag_sniper_v1.rmdl @i
SNIPER_AMMO                     4   w_loot_wep_ammo_sniper.rmdl @i
BOCEK                           4   /compound_bow/ /compound/
SENTINEL                        4   /sentinel/ @i
CHARGE_RIFLE                    4   /defender/ /chargerifle/
LONGBOW                         4   /rspn101_dmr/ @i
WINGMAN                         4   /b3wing/ /wingman/
KRABER                          4   /at_rifle/ /kraber/
SHOTGUN_WEAPON                  -1  w_loot_wep_ammo_shg.rmdl @i
SHOTGUN_WEAPON                  -1  /pstl_sa3/ /mozambique/
SHOTGUN_WEAPON                  -1  /eva8/ @i
SHOTGUN_WEAPON                  -1  /peacekeeper/ @i
SHOTGUN_WEAPON                  -1  /mastiff/ /mastiff_stgn/
HEAVY_WEAPON                    -1  w_loot_wep_ammo_hc.rmdl @i
HEAVY_WEAPON                    -1  /flatline/ @i
HEAVY_WEAPON                    -1  /m1a1_hemlok/ /hemlok/
HEAVY_WEAPON                    -1  /prowler/ /prowler_smg/
HEAVY_WEAPON                    -1  /3030repeater/ /repeater3030/
HEAVY_WEAPON                    -1  /dragon/ @i
HEAVY_WEAPON                    -1  /car/ @i
LIGHT_WEAPON                    -1  w_loot_wep_ammo_sc.rmdl @i
LIGHT_WEAPON                    -1  /g7/ /g2/
LIGHT_WEAPON                    -1  /lmg_hemlok/ /spitfire/
LIGHT_WEAPON                    -1  /r301/ /rspn101/
LIGHT_WEAPON                    -1  /r97/ /r99/
LIGHT_WEAPON                    -1  /alternator_smg/ /alternator/
LIGHT_WEAPON                    -1  /p2011/ /p2020/
ENERGY_WEAPON                   -1  w_loot_wep_ammo_nrg.rmdl @i
ENERGY_WEAPON                   -1  /nemesis/ @i
ENERGY_WEAPON                   -1  /hemlok_smg/ /volt/
ENERGY_WEAPON                   -1  /doubletake/ /tripletake/
ENERGY_WEAPON                   -1  /lstar/ @i
ENERGY_WEAPON                   -1  /hemlock_br/ /devotion/
ENERGY_WEAPON                   -1  /beam_ar/ /havoc/
ENERGY_WEAPON                   -1  /p2011_auto/ /re45/
SNIPER_WEAPON                   -1  w_loot_wep_ammo_sniper.rmdl @i
SNIPER_WEAPON                   -1  /compound_bow/ /compound/
SNIPER_WEAPON                   -1  /sentinel/ @i
SNIPER_WEAPON                   -1  /defender/ /chargerifle/
SNIPER_WEAPON                   -1  /rspn101_dmr/ @i
SNIPER_WEAPON                   -1  /b3wing/ /wingman/
SNIPER_WEAPON                   -1  /at_rifle/ /kraber/
SNIPER_WEAPON                   -1  w_loot_wep_mods_optic_sni_dcom.rmdl @i
SNIPER_WEAPON                   -1  w_loot_wep_mods_optic_sni_var_talon.rmdl @i
SNIPER_WEAPON                   -1  w_loot_wep_mods_optic_sni_threat_wyeon.rmdl @i
EPIC_GEAR                       -1  w_loot_wep_mods_suppr_v2b.rmdl @i
EPIC_GEAR                       -1  w_loot_wep_mods_lasersight_v1.rmdl @i
EPIC_GEAR                       -1  w_loot_wep_iso_stock_folded_regular.rmdl @i
EPIC_GEAR                       -1  w_loot_wep_iso_stock_folded_sniper.rmdl @i
EPIC_GEAR                       -1  w_loot_wep_mods_mag_v1b.rmdl @i
EPIC_GEAR                       -1  w_loot_wep_mods_mag_energy_v1.rmdl @i
EPIC_GEAR                       -1  w_loot_wep_mods_mag_v3b.rmdl @i
EPIC_GEAR                       -1  w_loot_wep_mods_mag_v2b.rmdl @i
EPIC_GEAR                       -1  w_loot_wep_mods_mag_sniper_v1.rmdl @i
EPIC_GEAR                       -1  w_loot_char_backpack_medium.rmdl @i
EPIC_GEAR                       -1  w_loot_char_backpack_heavy.rmdl @i
EPIC_GEAR                       -1  w_loot_wep_mods_optic_cq_hcog_r2.rmdl @i
EPIC_GEAR                       -1  w_loot_wep_mods_optic_cq_holo_var_2x.rmdl @i
EPIC_GEAR                       -1  w_loot_wep_mods_optic_rng_hcog_acgs.rmdl @i
EPIC_GEAR                       -1  w_loot_wep_mods_optic_rng_aog_var_r1.rmdl @i
SURVIVAL                        -1  w_loot_wep_iso_ultimate_accelerant.rmdl @i
SURVIVAL                        -1  w_loot_wep_iso_health_main_large.rmdl @i
SURVIVAL                        -1  w_loot_wep_iso_shield_battery_large.rmdl @i
SURVIVAL                        -1  loot_void_ring.rmdl @i
SURVIVAL                        -1  beacon_capsule_01.rmdl @i
SURVIVAL                        -1  evac_tower_loot.rmdl @i
