#pragma once
constexpr int WEAPON_R301 = 105;
constexpr int WEAPON_SENTINEL = 108;
constexpr int WEAPON_BOCEK = 111;
constexpr int WEAPON_RAMPAGE = 125;
constexpr int WEAPON_RAMPART_SHEILA_STATIONARY = 0;
constexpr int WEAPON_ALTERNATOR = 964;
constexpr int WEAPON_RE45 = 3144;
constexpr int WEAPON_CHARGE_RIFLE = 311;
constexpr int WEAPON_DEVOTION = 3199;
constexpr int WEAPON_LONGBOW = 3227;
constexpr int WEAPON_HAVOC = 1746;
constexpr int WEAPON_EVA8 = 899;
constexpr int WEAPON_FLATLINE = 1682;
constexpr int WEAPON_G7 = 355;
constexpr int WEAPON_HEMLOCK = 152;
constexpr int WEAPON_KRABER = 3425;
constexpr int WEAPON_LSTAR = 155;
constexpr int WEAPON_MASTIFF = 1230;
constexpr int WEAPON_MOZAMBIQUE = 3481;
constexpr int WEAPON_PROWLER = 3493;
constexpr int WEAPON_PEACEKEEPER = 291;
constexpr int WEAPON_R99 = 149;
constexpr int WEAPON_P2020 = 150;
constexpr int WEAPON_SPITFIRE = 3709;
constexpr int WEAPON_TRIPLE_TAKE = 3745;
constexpr int WEAPON_WINGMAN = 1047;
constexpr int WEAPON_VOLT = 3828;
constexpr int WEAPON_3030 = 1817;
constexpr int WEAPON_CAR = 3933;
constexpr int WEAPON_NEMESIS = 3971;
constexpr int WEAPON_MELEE = 0;
constexpr int WEAPON_THROWING_KNIFE = 0;

std::unordered_map<int, std::string> intToStringMap = {
    {WEAPON_R301, "WEAPON_R301"},
    {WEAPON_SENTINEL, "WEAPON_SENTINEL"},
    {WEAPON_BOCEK, "WEAPON_BOCEK"},
    {WEAPON_RAMPAGE, "WEAPON_RAMPAGE"},
    {WEAPON_RAMPART_SHEILA_STATIONARY, "WEAPON_RAMPART_SHEILA_STATIONARY"},
    {WEAPON_ALTERNATOR, "WEAPON_ALTERNATOR"},
    {WEAPON_RE45, "WEAPON_RE45"},
    {WEAPON_CHARGE_RIFLE, "WEAPON_CHARGE_RIFLE"},
    {WEAPON_DEVOTION, "WEAPON_DEVOTION"},
    {WEAPON_LONGBOW, "WEAPON_LONGBOW"},
    {WEAPON_HAVOC, "WEAPON_HAVOC"},
    {WEAPON_EVA8, "WEAPON_EVA8"},
    {WEAPON_FLATLINE, "WEAPON_FLATLINE"},
    {WEAPON_G7, "WEAPON_G7"},
    {WEAPON_HEMLOCK, "WEAPON_HEMLOCK"},
    {WEAPON_KRABER, "WEAPON_KRABER"},
    {WEAPON_LSTAR, "WEAPON_LSTAR"},
    {WEAPON_MASTIFF, "WEAPON_MASTIFF"},
    {WEAPON_MOZAMBIQUE, "WEAPON_MOZAMBIQUE"},
    {WEAPON_PROWLER, "WEAPON_PROWLER"},
    {WEAPON_PEACEKEEPER, "WEAPON_PEACEKEEPER"},
    {WEAPON_R99, "WEAPON_R99"},
    {WEAPON_P2020, "WEAPON_P2020"},
    {WEAPON_SPITFIRE, "WEAPON_SPITFIRE"},
    {WEAPON_TRIPLE_TAKE, "WEAPON_TRIPLE_TAKE"},
    {WEAPON_WINGMAN, "WEAPON_WINGMAN"},
    {WEAPON_VOLT, "WEAPON_VOLT"},
    {WEAPON_3030, "WEAPON_3030"},
    {WEAPON_CAR, "WEAPON_CAR"},
    {WEAPON_NEMESIS, "WEAPON_NEMESIS"},
    {WEAPON_MELEE, "WEAPON_MELEE"},
    {WEAPON_THROWING_KNIFE, "WEAPON_THROWING_KNIFE"}
    };

std::string WeaponName(int weaponId) {
    auto it = intToStringMap.find(weaponId);
    if (it != intToStringMap.end())
        return it->second;
    return "UNKNOWN! NEED WEAPONID UPDATE!?";
}
