#NAME                           SPEED GVT DLY  ADS
/pstl_sa3/ /mozambique/         10000 1.0 -300 NO  #MOZAMBIQUE
/eva8/ @w                       16000 1.0  250 NO  #EVA-8
/peacekeeper/ @w                20000 1.0 -950 NO  #PEACEKEEPER
/mastiff/ /mastiff_stgn/        16000 1.0 -800 NO  #MASTIFF
/flatline/ @w                   24000 1.3    0 NO  #FLATLINE
/m1a1_hemlok/ /hemlok/          27500 1.3    0 NO  #HEMLOK
/prowler/ /prowler_smg/         18000 1.2  400 NO  #PROWLER
/3030repeater/ /repeater3030/   29000 1.4  400 NO  #30-30
/dragon/ @w                     26500 1.4    0 NO  #RAMPAGE
/rampart_turret/ @w             26500 1.4    0 NO  #RAMPART
/car/ @w                        18000 1.1    0 NO  #C.A.R.
/g7/ /g2/                       30000 1.4  200 NO  #G7_SCOUT
/lmg_hemlok/ /spitfire/         27500 1.4    0 NO  #SPITFIRE
/r301/ /rspn101/                29000 1.3    0 NO  #R-301
/r97/ /r99/                     19000 1.2    0 NO  #R-99
/alternator_smg/ /alternator/   19000 1.2    0 NO  #ALTERNATOR
/p2011/ /p2020/                 18500 1.0    0 NO  #P2020
/nemesis/ @w                    31000 1.1  350 NO  #NEMESIS
/hemlok_smg/ /volt/             20000 1.0    0 NO  #VOLT
/doubletake/ /tripletake/       32000 1.4  550 NO  #TRIPLE_TAKE
/lstar/ @w                      24000 0.5    0 NO  #L-STAR
/hemlock_br/ /devotion/         33500 1.4    0 NO  #DEVOTION
/beam_ar/ /havoc/               30500 1.1    0 NO  #HAVOC
/p2011_auto/ /re45/             19500 1.0   -1 NO  #RE-45
/compound_bow/ /compound/       29000 1.4   -1 NO  #BOCEK
/sentinel/ @w                   31000 1.4 -999 NO  #SENTINEL
/defender/ /chargerifle/        33999 1.1   -1 NO  #CHARGE_RIFLE
/misc_vantage_ultimate/ @w      33999 1.1 -999 NO  #VANTAGE
/rspn101_dmr/ @w                31000 1.3 -999 NO  #LONGBOW
/b3wing/ /wingman/              18000 1.2  350 NO  #WINGMAN
/at_rifle/ /kraber/             29500 1.4 -999 NO  #KRABER
_shuriken_ @w                    2200 1.6    0 NO  #SHURIKEN
_frag_grenade_ @w                1300 1.0    0 NO  #FRAG
_thermite_grenade_ @w            1300 1.0    0 NO  #THERMITE
